#!/usr/bin/env python
import argparse
import subprocess

parser = argparse.ArgumentParser(prog="fire",
                                 description='Fire script for the default prediction service',
                                 usage='%(prog)s actions')
subparsers = parser.add_subparsers(title="actions", dest='command')

parser.add_argument("-v", "--verbose",
                    action="store_true",
                    dest="VERBOSE",
                    help="run in verbose mode")

parser_create = subparsers.add_parser("rebuild",
                                      help='Rebuild the container using docker-compose: docker-compose build.')

# Update
parser_update = subparsers.add_parser("start",
                                      help='Start the dev container using docker-compose: docker-compose up dev')
parser_update.add_argument('-logging',
                           required=True,
                           choices=['json', 'text', 'debug'])
args = parser.parse_args()
if args.command == 'rebuild':
    command = ["docker-compose",
               "build",
               "--build-arg",
               "APP_NAME=income-service",
               "--build-arg",
               "APP_VERSION=localdev",]
    # subprocess.check_call(command)
    print ('rebuilddddd')
elif args.command == 'start':
    logger = {
        "json": [
            "docker-compose",
            "run",
            "-e",
            "logging=json",
            "-p",
            "8000:8000",
            "dev",
            "uvicorn",
            "income_service.main:app",
            "--reload",
            "--host",
            "0.0.0.0",
        ],
        "text": [
            "docker-compose",
            "run",
            "-e",
            "logging=text",
            "-p",
            "8000:8000",
            "dev",
            "uvicorn",
            "income_service.main:app",
            "--reload",
            "--host",
            "0.0.0.0",
        ],
        "debug": [
            "docker-compose",
            "run",
            "-e",
            "logging=debug",
            "-p",
            "8000:8000",
            "dev",
            "uvicorn",
            "income_service.main:app",
            "--host",
            "0.0.0.0",
        ],
    }
    # subprocess.check_call(logger[args.logging])


# https://dbader.org/blog/how-to-make-command-line-commands-with-python