#!/usr/bin/env python
import argparse
import subprocess

parser = argparse.ArgumentParser(prog="fire",
                                 description='Fire script for the default prediction service')
subparsers = parser.add_subparsers(title="actions", dest='command')

parser.add_argument("-v", "--verbose",
                    action="store_true",
                    dest="VERBOSE",
                    help="run in verbose mode")

parser_create = subparsers.add_parser("rebuild",
                                      help='Rebuild the container using docker-compose: docker-compose build.')

# Update
parser_update = subparsers.add_parser("start",
                                      help='Start the dev container using docker-compose: docker-compose up dev')
args = parser.parse_args()
if args.command == 'rebuild':
    subprocess.check_call(
        [
            "docker-compose",
            "build",
            "--build-arg",
            "APP_NAME=income-service",
            "--build-arg",
            "APP_VERSION=localdev",
        ]
    )
elif args.command == 'start':
    print ('oooo')


# https://dbader.org/blog/how-to-make-command-line-commands-with-python