"""Added account table

Revision ID: f94500860f82
Revises: 
Create Date: 2020-04-02 06:46:41.294838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f94500860f82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary key for the table.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='When the record was inserted in the table.'),
    sa.Column('model_version', sa.String(length=100), nullable=False, comment='The version of the model'),
    sa.Column('model_description', sa.String(length=100), nullable=False, comment='The description of the model.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version'),
    comment='Information about models that have been deployed.'
    )
    op.create_index('model_version_index', 'model_metadata', ['model_version'], unique=False)
    op.create_table('default_predictions',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='The primary key for the table.'),
    sa.Column('SK_ID_CURR', sa.BigInteger(), nullable=False, comment='The loan ID'),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='When the record was inserted in the table.'),
    sa.Column('model_id', sa.Integer(), nullable=False, comment='Foreign key that references model_metadata.id.'),
    sa.Column('default_prob', sa.Float(), nullable=False, comment='The default probability by the model'),
    sa.ForeignKeyConstraint(['model_id'], ['model_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default_predictions')
    op.drop_index('model_version_index', table_name='model_metadata')
    op.drop_table('model_metadata')
    # ### end Alembic commands ###
